import { Card } from '../models/card.model';

export const MOCK_CARDS: Card[] = [
  {
    id: 1,
    name: 'Tupã',
    type: 'Deity',
    rarity: 'rare',
    cardNumber: 1,
    collectionSize: 45,
    collection: 'TUP-1: The First Peoples',
    imageUrl: 'https://placehold.co/280x244/2a1500/d4a017',
    flavorText: 'Lord of thunder and the sky, Tupã shaped the earth with lightning and filled the rivers with his tears of rain.',
    artistName: 'M. Cavalcante',
  },
  {
    id: 2,
    name: 'Iara',
    type: 'Spirit',
    rarity: 'uncommon',
    cardNumber: 2,
    collectionSize: 45,
    collection: 'TUP-1: The First Peoples',
    imageUrl: 'https://placehold.co/280x244/001a0f/52b788',
    flavorText: 'From beneath the dark waters she calls. Those who hear her song seldom find their way back to shore.',
    artistName: 'L. Ferreira',
  },
  {
    id: 3,
    name: 'Caipora',
    type: 'Spirit',
    rarity: 'common',
    cardNumber: 3,
    collectionSize: 45,
    collection: 'TUP-1: The First Peoples',
    imageUrl: 'https://placehold.co/280x244/141414/9ca3af',
    flavorText: 'Guardian of the hunt, she rides a peccary through the forest night, confounding those who take more than they need.',
  },
  {
    id: 4,
    name: 'Guaracy',
    type: 'Deity',
    rarity: 'rare',
    cardNumber: 4,
    collectionSize: 45,
    collection: 'TUP-1: The First Peoples',
    imageUrl: 'https://placehold.co/280x244/2a0f00/d4a017',
    flavorText: 'The Sun God watches all beneath him. His gaze is warmth; his anger, drought. The harvest answers to no one else.',
    artistName: 'M. Cavalcante',
  },
  {
    id: 5,
    name: 'Jaci',
    type: 'Deity',
    rarity: 'uncommon',
    cardNumber: 5,
    collectionSize: 45,
    collection: 'TUP-1: The First Peoples',
    imageUrl: 'https://placehold.co/280x244/000d1a/52b788',
    flavorText: 'Goddess of the moon, mother of night. She lights the path of travelers and whispers to the tides.',
  },
  {
    id: 6,
    name: 'Curupira',
    type: 'Creature',
    rarity: 'common',
    cardNumber: 6,
    collectionSize: 45,
    collection: 'TUP-1: The First Peoples',
    imageUrl: 'https://i.pinimg.com/736x/1d/cc/7e/1dcc7ee004fd2569799c03d20408af01.jpg',
    flavorText: 'Its feet point backward to mislead hunters. A child of the forest — fierce, wild, and unforgiving of trespass.',
    artistName: 'R. Nascimento',
  },
  {
    id: 7,
    name: 'Boitatá',
    type: 'Creature',
    rarity: 'uncommon',
    cardNumber: 7,
    collectionSize: 45,
    collection: 'TUP-1: The First Peoples',
    imageUrl: 'https://placehold.co/280x244/1a0a00/52b788',
    flavorText: 'A serpent of living fire, born from the floods of ages past. It hunts those who set the fields to burn.',
  },
  {
    id: 8,
    name: 'Anhangá',
    type: 'Spirit',
    rarity: 'rare',
    cardNumber: 8,
    collectionSize: 45,
    collection: 'TUP-1: The First Peoples',
    imageUrl: 'https://placehold.co/280x244/1a001a/d4a017',
    flavorText: 'The wandering evil. It takes the shape of a white deer with fire-red eyes to lure the doomed deeper into the jungle.',
    artistName: 'L. Ferreira',
  },
];
